### PR TITLE
New nav in index.html

### PR DESCRIPTION
**Pull request by MarcosCl98**
I have created a nav in index.html.
- This nav appears when we log in, otherwise it is not visible. It has a button that would reload the page (home), a button to see the list of contacts, another for chats and another to close the session.

- The changes made will not affect the functionality that you do in java script, since I use the same ids.

**It would look like this:**

The design is simple, but I think it would improve visually quite as it was before, if you like we can merge it, any criticism is allowed. :)

### CODE REVIEW

**Comment by martinlacorrona** [comment]
Its feel good

**Comment by srensamblador** [comment]
It's pretty but I'm worried integrating the navbar now would make the rest hard to work with JQuery, My recommendation would be to save your navbar for now and integrate it when the chat is already working.

For now simple views to make sure the chat works and once we get there we can see how to integrate the navigation.

What do you think?

**Comment by LuisBoto** [comment]
As Samuel says, it really looks good but maybe we should save it for later. I think we could just let the branch sit for now and merge it once we are a bit more advanced with the interface, just so we deal with it when we are ready

**Comment by MarcosCl98** [comment]
But my question is, what will affect the nav, that is, are still buttons, with the same id, if someone added for example the functionality of viewing contacts, if you use the id of the button, in this case friends, is the same that of the old html, with which the code in javascript would be the same. I do not know if I explained well ... I really just modified the look, the elements are the same. If someone can explain it to me, I would appreciate it.

**Pull request closed without merging**
