### PR TITLE
Features/refactor code

### PR DESCRIPTION
**Pull request by martinlacorrona**
Now UI only need class Chat.js for communicate with Chat Logic.

### CODE REVIEW

**Comment by martinlacorrona** [comment]
I have updated now the documentation.

**Comment by LuisBoto** [comment]
I wanted to ask @martinlacorrona and  @uo257493 about the TextParser script and the slashes method. I have been looking at the code and i don't quite get why this is necessary at all, since slashes are located only at the start and end of the file. Therefore, parsing seems futile; i think code never seems to enter the if blocks (file is always written in the same way to POD) and ends up returning just the JSON.parse of parts[1], which is basically the whole file. 

Please give me some insight on this, i think i may be missing something.

**Comment by srensamblador** [comment]
Tests are :ok_hand:

**Comment by uo257493** [comment]
@LuisBoto yes you are right main idea to use  the four slashes  were under the pretext to read a full RDF avoiding the use of a native library to treat this kind of file. For sure now it will be removed. If everybody agree i'll proceed

**Pull request merged**
