### PR TITLE
Features/login

### PR DESCRIPTION
**Pull request by JavierUrones**
The login has been updated, the changes are:
* The application icon changed from angular icon to solid icon.
* Add Solid logo in index.html
* Title of index.html has been modified.
* Selection of ID provider improved.

### CODE REVIEW

**Comment by srensamblador** [comment]
I like it, if everyone agrees let's merge this into develop

**Comment by martinlacorrona** [comment]
Okay.

**Comment by uo257493** [comment]
If anyone wants to custom it with a representative pic for our chat. (Just create a simple icon like whatsapp one) or don't now for me it's ok to merge into develop.

**Comment by srensamblador** [comment]
Let's leave the PR open until Monday just in case, but we can add the logo at any time, there's more important stuff to think about rn

**Pull request merged**
